[Interface]
PrivateKey = WM6LYgsGyTD9KNvvpo6rZPB9lE+RB/tH6reB+iMpyHc=
Address = 10.0.0.2/24, fd00::2/64

[Peer]
PublicKey = E8aWx/CO+VuEfG+mqp0RsdK+sWK7c3apFFKOQ/zjOzI=
AllowedIPs = 10.0.0.1/32, fd00::1/128

[Peer]
PublicKey = RsT/Yd49oazFR0NinQDbwIkRhLaexswX66VGHVbHzGE=
AllowedIPs = 10.0.0.3/32, fd00::3/128
