[Interface]
PrivateKey = gHENMX9KrI5VujkWQaHPPLzCT5x2PPx9hDozVzRUhV8=
Address = 10.0.0.1/24, fd00::1/64
ListenPort = 51820

[Peer]
PublicKey = T2b30sEqbgi+tS+MxgPszMVAP9n62yYwTrpLKRiKP1w=
AllowedIPs = 10.0.0.2/32, fd00::2/128

[Peer]
PublicKey = RsT/Yd49oazFR0NinQDbwIkRhLaexswX66VGHVbHzGE=
AllowedIPs = 10.0.0.3/32, fd00::3/128
