[Interface]
PrivateKey = iJF0C5DjHsY/uyzE9jUlKph1votABvecX3e4fm5walE=
Address = 10.0.0.3/24, fd00::3/64

[Peer]
PublicKey = E8aWx/CO+VuEfG+mqp0RsdK+sWK7c3apFFKOQ/zjOzI=
AllowedIPs = 10.0.0.1/32, fd00::1/128

[Peer]
PublicKey = T2b30sEqbgi+tS+MxgPszMVAP9n62yYwTrpLKRiKP1w=
AllowedIPs = 10.0.0.2/32, fd00::2/128
